# Default configuration for Alfreed
app_name: "alfreed"
version: "0.2.0"
debug: false
environment: "development"

# Model configuration
model:
  default_embedding_model: "zhihan1996/DNABERT-2-117M"
  max_token_length: 512  # Maximum number of tokens (not nucleotides)
  batch_size: 32
  device: "auto"  # auto, cpu, cuda
  cache_dir: null

# Search configuration
search:
  default_k: 10
  default_metric: "cosine"  # cosine, l2
  similarity_threshold: 0.8
  max_results_per_query: 5
  enable_alignment: false
  exclude_self_matches: true

# Alignment configuration
alignment:
  alignment_type: "local"
  gap_open_penalty: 10
  gap_extend_penalty: 1
  match_score: 2
  mismatch_penalty: -1

# Storage configuration
storage:
  data_dir: "./data"
  cache_dir: "./cache"
  output_dir: "./output"
  temp_dir: "./tmp"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_to_file: false
  log_file: null
  max_file_size: 10485760  # 10MB
  backup_count: 5
